apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-pod
  name: resource-pod
spec:
  containers:
  - image: nginx
    name: resource-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
resources:
  requests:
    memory: "10Gi"
    cpu: "8"
